import type { Exam, Question } from "@/lib/types";

/**
 * Seed question bank. SERVER-ONLY: this module contains answer keys and must
 * never be imported from a "use client" file. Candidates receive a stripped
 * copy via `toCandidateExam()` in ./repository.ts.
 */

const PHYSICS_CH1: Question[] = [
  {
    id: "phy-q1",
    topic: "ভৌত রাশি ও পরিমাপ",
    marks: 1,
    text: "নিচের কোনটি মৌলিক রাশি?",
    options: [
      { id: "a", text: "বল" },
      { id: "b", text: "বেগ" },
      { id: "c", text: "তড়িৎ প্রবাহ" },
      { id: "d", text: "কাজ" },
    ],
    correctOptionId: "c",
    explanation:
      "SI পদ্ধতিতে মৌলিক রাশি সাতটি: দৈর্ঘ্য, ভর, সময়, তাপমাত্রা, তড়িৎ প্রবাহ, দীপন তীব্রতা ও পদার্থের পরিমাণ। বল, বেগ ও কাজ এগুলো থেকে গঠিত লব্ধ রাশি।",
  },
  {
    id: "phy-q2",
    topic: "ভৌত রাশি ও পরিমাপ",
    marks: 1,
    text: "দীপন তীব্রতার SI একক কোনটি?",
    options: [
      { id: "a", text: "ক্যান্ডেলা" },
      { id: "b", text: "কেলভিন" },
      { id: "c", text: "মোল" },
      { id: "d", text: "লুমেন" },
    ],
    correctOptionId: "a",
    explanation: "দীপন তীব্রতার SI একক ক্যান্ডেলা (cd)। কেলভিন তাপমাত্রার, মোল পদার্থের পরিমাণের একক; লুমেন আলোক প্রবাহের লব্ধ একক।",
  },
  {
    id: "phy-q3",
    topic: "ভৌত রাশি ও পরিমাপ",
    marks: 1,
    text: "১ মাইক্রোমিটার (μm) সমান কত মিটার?",
    options: [
      { id: "a", text: "১০⁻³ m" },
      { id: "b", text: "১০⁻⁶ m" },
      { id: "c", text: "১০⁻⁹ m" },
      { id: "d", text: "১০⁻¹² m" },
    ],
    correctOptionId: "b",
    explanation: "মাইক্রো (μ) উপসর্গের মান ১০⁻⁶। তাই ১ μm = ১০⁻⁶ m। মিলি = ১০⁻³, ন্যানো = ১০⁻⁹, পিকো = ১০⁻¹²।",
  },
  {
    id: "phy-q4",
    topic: "ভৌত রাশি ও পরিমাপ",
    marks: 1,
    text: "স্লাইড ক্যালিপার্সের প্রধান স্কেলের ক্ষুদ্রতম এক ঘরের মান s এবং ভার্নিয়ার স্কেলের ঘর সংখ্যা n হলে ভার্নিয়ার ধ্রুবক কত?",
    options: [
      { id: "a", text: "s × n" },
      { id: "b", text: "n / s" },
      { id: "c", text: "s / n" },
      { id: "d", text: "s + n" },
    ],
    correctOptionId: "c",
    explanation: "ভার্নিয়ার ধ্রুবক VC = s / n। যেমন s = ১ mm ও n = ১০ হলে VC = ০.১ mm।",
  },
  {
    id: "phy-q5",
    topic: "ভৌত রাশি ও পরিমাপ",
    marks: 1,
    text: "স্ক্রু গজে স্ক্রুর ঘূর্ণনের দিক পরিবর্তন করলে যে ত্রুটি দেখা দেয় তাকে কী বলে?",
    options: [
      { id: "a", text: "শূন্য ত্রুটি" },
      { id: "b", text: "পিছট ত্রুটি" },
      { id: "c", text: "লম্বন ত্রুটি" },
      { id: "d", text: "এলোমেলো ত্রুটি" },
    ],
    correctOptionId: "b",
    explanation:
      "দীর্ঘ ব্যবহারে স্ক্রুর প্যাঁচ ক্ষয় হলে ঘূর্ণনের দিক বদলানোর সময় কিছুক্ষণ টুপি ঘুরলেও স্ক্রু সরে না। এটাই পিছট ত্রুটি (backlash error)। একই দিকে ঘুরিয়ে পাঠ নিলে এ ত্রুটি এড়ানো যায়।",
  },
  {
    id: "phy-q6",
    topic: "ভৌত রাশি ও পরিমাপ",
    marks: 1,
    text: "নিচের কোনটি ভেক্টর রাশি?",
    options: [
      { id: "a", text: "দ্রুতি" },
      { id: "b", text: "দূরত্ব" },
      { id: "c", text: "সরণ" },
      { id: "d", text: "ভর" },
    ],
    correctOptionId: "c",
    explanation: "সরণের মান ও দিক দুটোই আছে, তাই এটি ভেক্টর রাশি। দ্রুতি, দূরত্ব ও ভরের শুধু মান আছে, এরা স্কেলার।",
  },
];

const PHYSICS_CH2: Question[] = [
  {
    id: "phy-q7",
    topic: "গতি",
    marks: 1,
    text: "স্থির অবস্থান থেকে একটি বস্তু ২ m/s² সুষম ত্বরণে চলতে শুরু করল। ৫ সেকেন্ড পর এর বেগ কত হবে?",
    options: [
      { id: "a", text: "২.৫ m/s" },
      { id: "b", text: "৭ m/s" },
      { id: "c", text: "১০ m/s" },
      { id: "d", text: "২৫ m/s" },
    ],
    correctOptionId: "c",
    explanation: "v = u + at = ০ + ২ × ৫ = ১০ m/s।",
  },
  {
    id: "phy-q8",
    topic: "গতি",
    marks: 1,
    text: "স্থির অবস্থান থেকে ২ m/s² সুষম ত্বরণে চলা একটি বস্তু প্রথম ৫ সেকেন্ডে কত দূরত্ব অতিক্রম করবে?",
    options: [
      { id: "a", text: "১০ m" },
      { id: "b", text: "২৫ m" },
      { id: "c", text: "৫০ m" },
      { id: "d", text: "১২.৫ m" },
    ],
    correctOptionId: "b",
    explanation: "s = ut + ½at² = ০ + ½ × ২ × ৫² = ২৫ m।",
  },
  {
    id: "phy-q9",
    topic: "গতি",
    marks: 1,
    text: "৭২ km/h বেগকে m/s এককে প্রকাশ করলে কত হয়?",
    options: [
      { id: "a", text: "১০ m/s" },
      { id: "b", text: "২০ m/s" },
      { id: "c", text: "৩৬ m/s" },
      { id: "d", text: "২৫৯.২ m/s" },
    ],
    correctOptionId: "b",
    explanation: "১ km/h = ১০০০/৩৬০০ m/s = ৫/১৮ m/s। তাই ৭২ × ৫/১৮ = ২০ m/s।",
  },
  {
    id: "phy-q10",
    topic: "গতি",
    marks: 1,
    text: "বেগ-সময় লেখচিত্রের ঢাল কোন রাশি নির্দেশ করে?",
    options: [
      { id: "a", text: "সরণ" },
      { id: "b", text: "দ্রুতি" },
      { id: "c", text: "ত্বরণ" },
      { id: "d", text: "বল" },
    ],
    correctOptionId: "c",
    explanation: "ঢাল = বেগের পরিবর্তন ÷ সময় = ত্বরণ। আর লেখের নিচের ক্ষেত্রফল সরণ নির্দেশ করে।",
  },
  {
    id: "phy-q11",
    topic: "গতি",
    marks: 1,
    text: "২০ m/s বেগে চলমান একটি গাড়ি ব্রেক কষার ৪ সেকেন্ড পর থেমে গেল। গাড়িটির মন্দন কত?",
    options: [
      { id: "a", text: "৪ m/s²" },
      { id: "b", text: "৫ m/s²" },
      { id: "c", text: "৮০ m/s²" },
      { id: "d", text: "১৬ m/s²" },
    ],
    correctOptionId: "b",
    explanation: "a = (v − u) / t = (০ − ২০) / ৪ = −৫ m/s²। ঋণাত্মক ত্বরণই মন্দন, তাই মন্দন ৫ m/s²।",
  },
  {
    id: "phy-q12",
    topic: "গতি",
    marks: 1,
    text: "ভূপৃষ্ঠের কাছে মুক্তভাবে পড়ন্ত বস্তুর ত্বরণের আদর্শ মান প্রায় কত?",
    options: [
      { id: "a", text: "৯.৮ m/s²" },
      { id: "b", text: "৬.৬৭ m/s²" },
      { id: "c", text: "১.৬ m/s²" },
      { id: "d", text: "৯৮ m/s²" },
    ],
    correctOptionId: "a",
    explanation: "অভিকর্ষজ ত্বরণ g ≈ ৯.৮ m/s²। চাঁদে এর মান প্রায় ১.৬ m/s²।",
  },
];

const CHEMISTRY_CH3: Question[] = [
  {
    id: "chem-q1",
    topic: "পদার্থের গঠন",
    marks: 1,
    text: "পরমাণুর নিউক্লিয়াসে নিচের কোন কণিকাগুলো থাকে?",
    options: [
      { id: "a", text: "ইলেকট্রন ও প্রোটন" },
      { id: "b", text: "প্রোটন ও নিউট্রন" },
      { id: "c", text: "ইলেকট্রন ও নিউট্রন" },
      { id: "d", text: "শুধু নিউট্রন" },
    ],
    correctOptionId: "b",
    explanation: "পরমাণুর কেন্দ্র বা নিউক্লিয়াসে ধনাত্মক আধানযুক্ত প্রোটন ও আধানহীন নিউট্রন থাকে। ইলেকট্রনগুলো নিউক্লিয়াসের বাইরে বিভিন্ন কক্ষপথে ঘোরে।",
  },
  {
    id: "chem-q2",
    topic: "পদার্থের গঠন",
    marks: 1,
    text: "বোর পরমাণু মডেল কত সালে প্রস্তাবিত হয়?",
    options: [
      { id: "a", text: "১৯১১" },
      { id: "b", text: "১৯১৩" },
      { id: "c", text: "১৯১৯" },
      { id: "d", text: "১৯২৫" },
    ],
    correctOptionId: "b",
    explanation: "নীলস বোর ১৯১৩ সালে ম্যাক্স প্ল্যাঙ্কের কোয়ান্টাম তত্ত্বের ওপর ভিত্তি করে পরমাণু মডেল প্রস্তাব করেন। ১৯১১ সালে বিজ্ঞানী রাদারফোর্ড তাঁর মডেল দেন।",
  },
  {
    id: "chem-q3",
    topic: "পদার্থের গঠন",
    marks: 1,
    text: "ক্লোরিনের (Cl) পারমাণবিক সংখ্যা কত?",
    options: [
      { id: "a", text: "১৫" },
      { id: "b", text: "১৬" },
      { id: "c", text: "১৭" },
      { id: "d", text: "৩৫" },
    ],
    correctOptionId: "c",
    explanation: "ক্লোরিনের প্রোটন সংখ্যা বা পারমাণবিক সংখ্যা ১৭ এবং এর গড় আপেক্ষিক পারমাণবিক ভর ৩৫.৫।",
  },
  {
    id: "chem-q4",
    topic: "পদার্থের গঠন",
    marks: 1,
    text: "আইসোটোপসমূহের মধ্যে নিচের কোনটি সর্বদা সমান থাকে?",
    options: [
      { id: "a", text: "ভর সংখ্যা" },
      { id: "b", text: "নিউট্রন সংখ্যা" },
      { id: "c", text: "প্রোটন সংখ্যা" },
      { id: "d", text: "যোজনী" },
    ],
    correctOptionId: "c",
    explanation: "যেসব পরমাণুর প্রোটন সংখ্যা সমান কিন্তু ভর সংখ্যা ও নিউট্রন সংখ্যা ভিন্ন, তাদেরকে পরস্পরের আইসোটোপ বলে।",
  },
  {
    id: "chem-q5",
    topic: "পদার্থের গঠন",
    marks: 1,
    text: "Na⁺ ক্যাটায়নে মোট ইলেকট্রন সংখ্যা কতটি?",
    options: [
      { id: "a", text: "১০" },
      { id: "b", text: "১১" },
      { id: "c", text: "১২" },
      { id: "d", text: "৯" },
    ],
    correctOptionId: "a",
    explanation: "সোডিয়ামের (Na) পারমাণবিক সংখ্যা ১১। Na⁺ আয়ন ১টি ইলেকট্রন ত্যাগ করে গঠিত হয়, তাই এতে ১১ - ১ = ১০টি ইলেকট্রন থাকে।",
  },
  {
    id: "chem-q6",
    topic: "পদার্থের গঠন",
    marks: 1,
    text: "নিষ্ক্রিয় গ্যাস হিলিয়ামের (He) সর্ববহিঃস্থ স্তরে কয়টি ইলেকট্রন থাকে?",
    options: [
      { id: "a", text: "১টি" },
      { id: "b", text: "২টি" },
      { id: "c", text: "৮টি" },
      { id: "d", text: "১৮টি" },
    ],
    correctOptionId: "b",
    explanation: "হিলিয়ামের ইলেকট্রন বিন্যাস 1s²। এটি দ্বৈত নিয়ম মেনে চলে এবং এর বহিঃস্থ শক্তিস্তরে ২টি ইলেকট্রন বিদ্যমান।",
  },
];

const CHEMISTRY_MODEL_01: Question[] = [
  {
    id: "chem-m1",
    topic: "পর্যায় সারণি",
    marks: 1,
    text: "আধুনিক পর্যায় সারণির মূল ভিত্তি কী?",
    options: [
      { id: "a", text: "পারমাণবিক ভর" },
      { id: "b", text: "পারমাণবিক সংখ্যা ও ইলেকট্রন বিন্যাস" },
      { id: "c", text: "গলনাঙ্ক ও স্ফুটনাঙ্ক" },
      { id: "d", text: "ঘনত্ব" },
    ],
    correctOptionId: "b",
    explanation: "আধুনিক পর্যায় সারণি মৌলসমূহের পারমাণবিক সংখ্যা এবং সর্ববহিঃস্থ স্তরের ইলেকট্রন বিন্যাসের ওপর ভিত্তি করে তৈরি।",
  },
  {
    id: "chem-m2",
    topic: "রাসায়নিক বন্ধন",
    marks: 1,
    text: "খাবার লবণ (NaCl) কোন ধরনের বন্ধন দ্বারা গঠিত?",
    options: [
      { id: "a", text: "সমযোজী বন্ধন" },
      { id: "b", text: "আয়নিক বন্ধন" },
      { id: "c", text: "ধাতব বন্ধন" },
      { id: "d", text: "হাইড্রোজেন বন্ধন" },
    ],
    correctOptionId: "b",
    explanation: "ধাতু সোডিয়াম (Na) ও অধাতু ক্লোরিন (Cl) এর মধ্যে ইলেকট্রন আদান-প্রদানের মাধ্যমে আয়নিক বা তড়িৎযোজী বন্ধন গঠিত হয়।",
  },
  {
    id: "chem-m3",
    topic: "মোল ও রাসায়নিক গণনা",
    marks: 1,
    text: "প্রমাণ তাপমাত্রা ও চাপে (STP) ১ মোল যেকোনো গ্যাসের আয়তন কত লিটার?",
    options: [
      { id: "a", text: "২২.৪ লিটার" },
      { id: "b", text: "২৪.৭৮৯ লিটার" },
      { id: "c", text: "২০.৪ লিটার" },
      { id: "d", text: "১১.২ লিটার" },
    ],
    correctOptionId: "a",
    explanation: "STP তে যেকোনো গ্যাসের ১ মোলের মোলার আয়তন ২২.৪ L (বা ২২.৪ dm³)।",
  },
  {
    id: "chem-m4",
    topic: "পর্যায় সারণি",
    marks: 1,
    text: "কোন গ্রুপটিকে হ্যালোজেন গ্রুপ বলা হয়?",
    options: [
      { id: "a", text: "গ্রুপ ১" },
      { id: "b", text: "গ্রুপ ২" },
      { id: "c", text: "গ্রুপ ১৭" },
      { id: "d", text: "গ্রুপ ১৮" },
    ],
    correctOptionId: "c",
    explanation: "গ্রুপ ১৭ এর মৌলসমূহকে (F, Cl, Br, I, At) লবণ উৎপাদক বা হ্যালোজেন মৌল বলা হয়।",
  },
  {
    id: "chem-m5",
    topic: "রাসায়নিক বিক্রিয়া",
    marks: 1,
    text: "কোন রাসায়নিক বিক্রিয়ায় ইলেকট্রন গ্রহণ ঘটে?",
    options: [
      { id: "a", text: "জারণ" },
      { id: "b", text: "বিজারণ" },
      { id: "c", text: "দহন" },
      { id: "d", text: "বিয়োজন" },
    ],
    correctOptionId: "b",
    explanation: "আধুনিক ইলেকট্রনীয় ধারণায় ইলেকট্রন বর্জন হলো জারণ এবং ইলেকট্রন গ্রহণ হলো বিজারণ।",
  },
  {
    id: "chem-m6",
    topic: "অ্যাসিড ও ক্ষারক",
    marks: 1,
    text: "বিশুদ্ধ পানির pH এর মান কত?",
    options: [
      { id: "a", text: "০" },
      { id: "b", text: "৭" },
      { id: "c", text: "১৪" },
      { id: "d", text: "১" },
    ],
    correctOptionId: "b",
    explanation: "২৫° সেলসিয়াস তাপমাত্রায় নিরপেক্ষ বা বিশুদ্ধ পানির pH এর মান ৭।",
  },
];

const HMATH_CH2: Question[] = [
  {
    id: "hmath-q1",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "P(x) = x³ − 6x² + 11x − 6 হলে P(1) এর মান কত?",
    options: [
      { id: "a", text: "০" },
      { id: "b", text: "১" },
      { id: "c", text: "৬" },
      { id: "d", text: "-৬" },
    ],
    correctOptionId: "a",
    explanation: "P(1) = 1³ − 6(1)² + 11(1) − 6 = 1 − 6 + 11 − 6 = 0। সুতরাং (x − 1) বহুপদীটির একটি উৎপাদক।",
  },
  {
    id: "hmath-q2",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "P(x) = 5x⁴ − 3x² + 7 বহুপদীর মুখ্য সহগ ও মাত্রা যথাক্রমে কত?",
    options: [
      { id: "a", text: "৪ ও ৫" },
      { id: "b", text: "৫ ও ৪" },
      { id: "c", text: "৭ ও ৪" },
      { id: "d", text: "৫ ও ২" },
    ],
    correctOptionId: "b",
    explanation: "সর্বোচ্চ ঘাতযুক্ত পদ 5x⁴। এখানে মাত্রা হলো ৪ এবং মুখ্য পদের সহগ (মুখ্য সহগ) হলো ৫।",
  },
  {
    id: "hmath-q3",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "যদি f(x, y, z) = x² + y² + z² − xy − yz − zx হয়, তবে রাশিটি কী প্রকৃতির?",
    options: [
      { id: "a", text: "শুধু প্রতিসম রাশি" },
      { id: "b", text: "চক্র-ক্রমিক ও প্রতিসম উভয়ই" },
      { id: "c", text: "অপ্রতিসম রাশি" },
      { id: "d", text: "এক চলকবিশিষ্ট রাশি" },
    ],
    correctOptionId: "b",
    explanation: "যেকোনো দুটি চলক অদলবদল করলে রাশির মান অপরিবর্তিত থাকে (প্রতিসম) এবং x→y, y→z, z→x বসালেও অপরিবর্তিত থাকে (চক্র-ক্রমিক)।",
  },
  {
    id: "hmath-q4",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "P(x) বহুপদীকে (ax + b) দ্বারা ভাগ করলে ভাগশেষ কত হবে?",
    options: [
      { id: "a", text: "P(b/a)" },
      { id: "b", text: "P(−b/a)" },
      { id: "c", text: "P(−a/b)" },
      { id: "d", text: "P(a/b)" },
    ],
    correctOptionId: "b",
    explanation: "ভাগশেষ উপপাদ্য অনুসারে, ax + b = 0 হলে x = −b/a, তাই ভাগশেষ হবে P(−b/a)।",
  },
  {
    id: "hmath-q5",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "নিচের কোন ভগ্নাংশটি প্রকৃত ভগ্নাংশ?",
    options: [
      { id: "a", text: "(x² + 1) / (x + 2)" },
      { id: "b", text: "(x + 1) / (x² + 3)" },
      { id: "c", text: "(x² + 1) / (x² − 4)" },
      { id: "d", text: "(x³ + 2) / (x² + 1)" },
    ],
    correctOptionId: "b",
    explanation: "যে মূলদ ভগ্নাংশের লবের মাত্রা হরের মাত্রার চেয়ে ছোট, তাকে প্রকৃত ভগ্নাংশ বলে। (x + 1)/(x² + 3) এ লবের মাত্রা ১ এবং হরের মাত্রা ২।",
  },
  {
    id: "hmath-q6",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "a³ + b³ + c³ − 3abc এর উৎপাদক বিশ্লেষিত রূপ কোনটি?",
    options: [
      { id: "a", text: "(a + b + c)(a² + b² + c² − ab − bc − ca)" },
      { id: "b", text: "(a + b + c)(a² + b² + c² + ab + bc + ca)" },
      { id: "c", text: "(a − b − c)(a² + b² + c² + ab + bc + ca)" },
      { id: "d", text: "(a + b − c)(a² + b² − c²)" },
    ],
    correctOptionId: "a",
    explanation: "সূত্রানুসারে, a³ + b³ + c³ − 3abc = (a + b + c)(a² + b² + c² − ab − bc − ca) = ½(a + b + c){(a−b)² + (b−c)² + (c−a)²}।",
  },
];

const HMATH_LIVE: Question[] = [
  {
    id: "hmath-l1",
    topic: "ত্রিকোণমিতি",
    marks: 1,
    text: "১ রেডিয়ান সমান কত ডিগ্রি (প্রায়)?",
    options: [
      { id: "a", text: "৫৭.৩°" },
      { id: "b", text: "৬০°" },
      { id: "c", text: "৪৫°" },
      { id: "d", text: "৯০°" },
    ],
    correctOptionId: "a",
    explanation: "১ রেডিয়ান = (১৮০ / π)° ≈ ৫৭.২৯৫৭° বা প্রায় ৫৭.৩°। রেডিয়ান একটি ধ্রুব কোণ।",
  },
  {
    id: "hmath-l2",
    topic: "ত্রিকোণমিতি",
    marks: 1,
    text: "ঘড়ির ঘণ্টার কাঁটা এবং মিনিটের কাঁটা ৭:২০ মিনিটে কত ডিগ্রি কোণ উৎপন্ন করে?",
    options: [
      { id: "a", text: "১০০°" },
      { id: "b", text: "১১০°" },
      { id: "c", text: "১২০°" },
      { id: "d", text: "১০৫°" },
    ],
    correctOptionId: "a",
    explanation: "কোণ θ = |(60H − 11M) / 2| = |(60×7 − 11×20) / 2| = |(420 − 220) / 2| = 200 / 2 = ১০০°।",
  },
  {
    id: "hmath-l3",
    topic: "জ্যামিতি",
    marks: 1,
    text: "একটি সমবাহু ত্রিভুজের বাহুর দৈর্ঘ্য 4 cm হলে এর ক্ষেত্রফল কত cm²?",
    options: [
      { id: "a", text: "৪√৩" },
      { id: "b", text: "৮√৩" },
      { id: "c", text: "১৬√৩" },
      { id: "d", text: "১২" },
    ],
    correctOptionId: "a",
    explanation: "সমবাহু ত্রিভুজের ক্ষেত্রফল = (√3 / 4) × a² = (√3 / 4) × 4² = (√3 / 4) × 16 = 4√3 cm²।",
  },
  {
    id: "hmath-l4",
    topic: "স্থানাঙ্ক জ্যামিতি",
    marks: 1,
    text: "(2, 3) এবং (5, 7) বিন্দুদ্বয়ের মধ্যকার দূরত্ব কত?",
    options: [
      { id: "a", text: "৪ একক" },
      { id: "b", text: "৫ একক" },
      { id: "c", text: "৬ একক" },
      { id: "d", text: "৭ একক" },
    ],
    correctOptionId: "b",
    explanation: "দূরত্ব d = √{(5 − 2)² + (7 − 3)²} = √{3² + 4²} = √{9 + 16} = √25 = ৫ একক।",
  },
  {
    id: "hmath-l5",
    topic: "অসীম ধারা",
    marks: 1,
    text: "১ + ½ + ¼ + ⅛ + ... অসীম গুণোত্তর ধারার অসীমতক সমষ্টি কত?",
    options: [
      { id: "a", text: "১" },
      { id: "b", text: "১.৫" },
      { id: "c", text: "২" },
      { id: "d", text: "অসীম" },
    ],
    correctOptionId: "c",
    explanation: "এখানে a = 1, r = ½ < 1। অসীমতক সমষ্টি S∞ = a / (1 − r) = 1 / (1 − ½) = 1 / ½ = ২।",
  },
  {
    id: "hmath-l6",
    topic: "সম্ভাবনা",
    marks: 1,
    text: "একটি নিরপেক্ষ ছক্কা নিক্ষেপ করলে মৌলিক সংখ্যা উঠার সম্ভাবনা কত?",
    options: [
      { id: "a", text: "১/৬" },
      { id: "b", text: "১/৩" },
      { id: "c", text: "১/২" },
      { id: "d", text: "২/৩" },
    ],
    correctOptionId: "c",
    explanation: "ছক্কায় মোট ফলাফল {১, ২, ৩, ৪, ৫, ৬} = ৬টি। মৌলিক সংখ্যা {২, ৩, ৫} = ৩টি। সম্ভাবনা = ৩/৬ = ১/২।",
  },
];

const BIOLOGY_CH2: Question[] = [
  {
    id: "bio-q1",
    topic: "জীবকোষ ও টিস্যু",
    marks: 1,
    text: "কোষের শক্তিঘর (Power House) কাকে বলা হয়?",
    options: [
      { id: "a", text: "রাইবোজোম" },
      { id: "b", text: "লাইসোজোম" },
      { id: "c", text: "মাইটোকন্ড্রিয়া" },
      { id: "d", text: "গলজি বস্তু" },
    ],
    correctOptionId: "c",
    explanation: "মাইটোকন্ড্রিয়ায় শ্বসন প্রক্রিয়ায় ক্রেবস চক্র ও ইলেকট্রন ট্রান্সপোর্ট চেইন সম্পন্ন হয় এবং সর্বাধিক ATP শক্তি উৎপন্ন হয়, তাই একে কোষের শক্তিঘর বলে।",
  },
  {
    id: "bio-q2",
    topic: "জীবকোষ ও টিস্যু",
    marks: 1,
    text: "উদ্ভিদকোষের কোন অঙ্গাণু সালোকসংশ্লেষণ প্রক্রিয়ার সাথে সরাসরি জড়িত?",
    options: [
      { id: "a", text: "ক্লোরোপ্লাস্ট" },
      { id: "b", text: "ক্রোমোপ্লাস্ট" },
      { id: "c", text: "লিউcop্লাস্ট" },
      { id: "d", text: "সেন্ট্রোজোম" },
    ],
    correctOptionId: "a",
    explanation: "ক্লোরোপ্লাস্টে সবুজ রঞ্জক পদার্থ ক্লোরোফিল থাকে, যা সৌরশক্তি শোষণ করে শর্করা জাতীয় খাদ্য তৈরিতে অংশ নেয়।",
  },
  {
    id: "bio-q3",
    topic: "জীবকোষ ও টিস্যু",
    marks: 1,
    text: "মানবদেহের দীর্ঘতম কোষ কোনটি?",
    options: [
      { id: "a", text: "যকৃৎ কোষ" },
      { id: "b", text: "নিউরন (স্নায়ুকোষ)" },
      { id: "c", text: "লোহিত রক্তকণিকা" },
      { id: "d", text: "অস্থিকোষ" },
    ],
    correctOptionId: "b",
    explanation: "স্নায়ুতন্ত্রের গঠন ও কাজের একক নিউরন মানবদেহের সবচেয়ে দীর্ঘ কোষ, যা প্রায় ১ মিটার পর্যন্ত লম্বা হতে পারে।",
  },
  {
    id: "bio-q4",
    topic: "জীবকোষ ও টিস্যু",
    marks: 1,
    text: "রক্ত নিচের কোন ধরনের টিস্যু বা কলার অন্তর্গত?",
    options: [
      { id: "a", text: "আবরণী কলা" },
      { id: "b", text: "পেশি কলা" },
      { id: "c", text: "তরল যোজক কলা" },
      { id: "d", text: "স্নায়ু কলা" },
    ],
    correctOptionId: "c",
    explanation: "রক্ত একটি ক্ষারীয়, তরল যোজক কলা (Fluid Connective Tissue)। এর মাত্রিকা তরল যা রক্তরস নামে পরিচিত।",
  },
  {
    id: "bio-q5",
    topic: "জীবকোষ ও টিস্যু",
    marks: 1,
    text: "কোষে প্রোটিন তৈরির কারখানা বা প্রোটিন সংশ্লেষণকারী অঙ্গাণু কোনটি?",
    options: [
      { id: "a", text: "রাইবোজোম" },
      { id: "b", text: "সেন্ট্রিওল" },
      { id: "c", text: "ভ্যাকুওল" },
      { id: "d", text: "পেরোক্সিজোম" },
    ],
    correctOptionId: "a",
    explanation: "রাইবোজোমে এমআরএনএ নির্দেশ অনুযায়ী অ্যামিনো অ্যাসিডের পলিপেপটাইড শৃঙ্খল গঠিত হয়, তাই একে প্রোটিন তৈরির কারখানা বলে।",
  },
  {
    id: "bio-q6",
    topic: "জীবকোষ ও টিস্যু",
    marks: 1,
    text: "জীবদেহের বংশগতির ভৌত ভিত্তি (Physical Basis of Heredity) কোনটি?",
    options: [
      { id: "a", text: "জিন" },
      { id: "b", text: "ক্রোমোজোম" },
      { id: "c", text: "সাইটোপ্লাজম" },
      { id: "d", text: "নিউক্লিওলাস" },
    ],
    correctOptionId: "b",
    explanation: "ক্রোমোজোম হলো বংশগতির ভৌত ভিত্তি, আর ডিএনএ/জিন হলো বংশগতির আণবিক ও রাসায়নিক ভিত্তি।",
  },
];

const BIOLOGY_MODEL_01: Question[] = [
  {
    id: "bio-m1",
    topic: "কোষ বিভাজন",
    marks: 1,
    text: "মানবদেহের জনন মাতৃকোষে কোন কোষ বিভাজন প্রক্রিয়া ঘটে?",
    options: [
      { id: "a", text: "অ্যামাইটোসিস" },
      { id: "b", text: "মাইটোসিস" },
      { id: "c", text: "মিয়োসিস" },
      { id: "d", text: "দ্বি-বিভাজন" },
    ],
    correctOptionId: "c",
    explanation: "জনন মাতৃকোষে মিয়োসিস বিভাজনের ফলে ক্রোমোজোম সংখ্যা অর্ধেক হয়ে হ্যাপ্লয়েড গ্যামেট (শুক্রাণু ও ডিম্বাণু) তৈরি হয়।",
  },
  {
    id: "bio-m2",
    topic: "সালোকসংশ্লেষণ",
    marks: 1,
    text: "সালোকসংশ্লেষণ প্রক্রিয়ায় উপজাত হিসেবে কোন গ্যাস নির্গত হয়?",
    options: [
      { id: "a", text: "কার্বন ডাই-অক্সাইড" },
      { id: "b", text: "অক্সিজেন" },
      { id: "c", text: "নাইট্রোজেন" },
      { id: "d", text: "মিথেন" },
    ],
    correctOptionId: "b",
    explanation: "পানির আলোক বিভাজন (ফোটোলাইসিস) প্রক্রিয়ায় পানি ভেঙে অক্সিজেন উপজাত হিসেবে পরিবেশে মুক্ত হয়।",
  },
  {
    id: "bio-m3",
    topic: "রক্ত সংবহন",
    marks: 1,
    text: "সর্বজনীন দাতা (Universal Donor) বলা হয় কোন রক্তের গ্রুপকে?",
    options: [
      { id: "a", text: "A" },
      { id: "b", text: "B" },
      { id: "c", text: "AB" },
      { id: "d", text: "O" },
    ],
    correctOptionId: "d",
    explanation: "রক্তের 'O' গ্রুপে কোনো অ্যান্টিজেন (A বা B) থাকে না, ফলে এই গ্রুপের রক্ত যেকোনো ব্যক্তিকে নিরাপদে দেওয়া যায়।",
  },
  {
    id: "bio-m4",
    topic: "শ্বসন",
    marks: 1,
    text: "সবাত শ্বসনে এক অণু গ্লুকোজ জারিত হয়ে মোট কতটি ATP উৎপন্ন হয় (আধুনিক হিসাব)?",
    options: [
      { id: "a", text: "৩৮টি" },
      { id: "b", text: "৩৬টি (বা ৩২/৩৮)" },
      { id: "c", text: "২৪টি" },
      { id: "d", text: "২টি" },
    ],
    correctOptionId: "b",
    explanation: "সবাত শ্বসনে এক অণু গ্লুকোজ সম্পূর্ণরূপে জারিত হলে মোট ৩৬ থেকে ৩৮ অণু এটিপি শক্তি তৈরি হয়।",
  },
  {
    id: "bio-m5",
    topic: "রেচন তন্ত্র",
    marks: 1,
    text: "বৃক্কের গঠন ও কাজের একক কোনটি?",
    options: [
      { id: "a", text: "নিউরন" },
      { id: "b", text: "নেফ্রন" },
      { id: "c", text: "অ্যালভিওলাই" },
      { id: "d", text: "পেলভিস" },
    ],
    correctOptionId: "b",
    explanation: "মানুষের প্রতিটি বৃক্কে প্রায় ১০-১২ লক্ষ নেফ্রন থাকে, যা মূত্র তৈরিতে রক্ত ফিল্টার করে।",
  },
  {
    id: "bio-m6",
    topic: "বংশগতি",
    marks: 1,
    text: "গ্রেগর জোহান মেন্ডেল বংশগতির গবেষণায় কোন উদ্ভিদ ব্যবহার করেছিলেন?",
    options: [
      { id: "a", text: "গম গাছ" },
      { id: "b", text: "মোটরশুঁটি গাছ" },
      { id: "c", text: "ধান গাছ" },
      { id: "d", text: "সরিষা গাছ" },
    ],
    correctOptionId: "b",
    explanation: "মেন্ডেল সাত জোড়া বিপরীতধর্মী বৈশিষ্ট্য নিয়ে বাগান মোটরশুঁটি (Pisum sativum) উদ্ভিদে দীর্ঘদিন সংকরায়ন পরীক্ষা করেন।",
  },
];

const MATH_CH3: Question[] = [
  {
    id: "math-q1",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "যদি a + b = 5 এবং ab = 6 হয়, তবে a² + b² এর মান কত?",
    options: [
      { id: "a", text: "১৩" },
      { id: "b", text: "১৭" },
      { id: "c", text: "২৫" },
      { id: "d", text: "১৯" },
    ],
    correctOptionId: "a",
    explanation: "a² + b² = (a + b)² − 2ab = 5² − 2(6) = 25 − 12 = ১৩।",
  },
  {
    id: "math-q2",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "x + 1/x = 3 হলে x³ + 1/x³ এর মান কত?",
    options: [
      { id: "a", text: "২৭" },
      { id: "b", text: "১৮" },
      { id: "c", text: "৩৬" },
      { id: "d", text: "৯" },
    ],
    correctOptionId: "b",
    explanation: "x³ + 1/x³ = (x + 1/x)³ − 3(x + 1/x) = 3³ − 3(3) = 27 − 9 = ১৮।",
  },
  {
    id: "math-q3",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "x² − 5x + 6 এর উৎপাদকে বিশ্লেষিত রূপ কোনটি?",
    options: [
      { id: "a", text: "(x − 2)(x − 3)" },
      { id: "b", text: "(x + 2)(x + 3)" },
      { id: "c", text: "(x − 1)(x − 6)" },
      { id: "d", text: "(x + 1)(x − 6)" },
    ],
    correctOptionId: "a",
    explanation: "x² − 5x + 6 = x² − 2x − 3x + 6 = x(x − 2) − 3(x − 2) = (x − 2)(x − 3)।",
  },
  {
    id: "math-q4",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "a² − b² এর উৎপাদক সূত্র কোনটি?",
    options: [
      { id: "a", text: "(a − b)²" },
      { id: "b", text: "(a + b)(a − b)" },
      { id: "c", text: "(a + b)² − 2ab" },
      { id: "d", text: "(a − b)(a² + ab + b²)" },
    ],
    correctOptionId: "b",
    explanation: "বর্গের অন্তর সূত্র অনুযায়ী: a² − b² = (a + b)(a − b)।",
  },
  {
    id: "math-q5",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "যদি x − y = 4 এবং xy = 3 হয়, তবে (x + y)² এর মান কত?",
    options: [
      { id: "a", text: "১৬" },
      { id: "b", text: "২৮" },
      { id: "c", text: "২২" },
      { id: "d", text: "১০" },
    ],
    correctOptionId: "b",
    explanation: "(x + y)² = (x − y)² + 4xy = 4² + 4(3) = 16 + 12 = ২৮।",
  },
  {
    id: "math-q6",
    topic: "বীজগাণিতিক রাশি",
    marks: 1,
    text: "p⁴ − 1 এর উৎপাদকে বিশ্লেষিত রূপ কোনটি?",
    options: [
      { id: "a", text: "(p² + 1)(p + 1)(p − 1)" },
      { id: "b", text: "(p² − 1)²" },
      { id: "c", text: "(p + 1)³(p − 1)" },
      { id: "d", text: "(p² + 1)(p² + 1)" },
    ],
    correctOptionId: "a",
    explanation: "p⁴ − 1 = (p²)² − 1² = (p² + 1)(p² − 1) = (p² + 1)(p + 1)(p − 1)।",
  },
];

const HSC_PHYSICS_VEC: Question[] = [
  {
    id: "hsc-phy-q1",
    topic: "ভেক্টর",
    marks: 1,
    text: "দুটি সমমানের ভেক্টরের লব্ধির মান এদের যেকোনো একটির সমান হলে ভেক্টরদ্বয়ের মধ্যবর্তী কোণ কত?",
    options: [
      { id: "a", text: "৬০°" },
      { id: "b", text: "৯০°" },
      { id: "c", text: "১২০°" },
      { id: "d", text: "১৮০°" },
    ],
    correctOptionId: "c",
    explanation: "R² = P² + Q² + 2PQ cosα। এখানে R = P = Q হলে P² = 2P²(1 + cosα) ⇒ cosα = −½ ⇒ α = ১২০°।",
  },
  {
    id: "hsc-phy-q2",
    topic: "ভেক্টর",
    marks: 1,
    text: "দুটি ভেক্টর পরস্পর লম্ব হওয়ার শর্ত কোনটি?",
    options: [
      { id: "a", text: "A · B = 0" },
      { id: "b", text: "A × B = 0" },
      { id: "c", text: "A + B = 0" },
      { id: "d", text: "A / B = 0" },
    ],
    correctOptionId: "a",
    explanation: "স্কেলার গুণন A · B = AB cosθ। দুটি ভেক্টর লম্ব হলে θ = ৯০°, ফলে cos ৯০° = ০ এবং A · B = ০।",
  },
  {
    id: "hsc-phy-q3",
    topic: "ভেক্টর",
    marks: 1,
    text: "A = 2î + 2ĵ − k̂ ভেক্টরটির মান কত?",
    options: [
      { id: "a", text: "৩" },
      { id: "b", text: "৫" },
      { id: "c", text: "√৭" },
      { id: "d", text: "৯" },
    ],
    correctOptionId: "a",
    explanation: "|A| = √{2² + 2² + (−1)²} = √{4 + 4 + 1} = √9 = ৩ একক।",
  },
  {
    id: "hsc-phy-q4",
    topic: "ভেক্টর",
    marks: 1,
    text: "কোনো ভেক্টরের কার্ল (Curl) শূন্য হলে ভেক্টরটি কী প্রকৃতির?",
    options: [
      { id: "a", text: "ঘূর্ণনশীল" },
      { id: "b", text: "অঘূর্ণনশীল ও সংরক্ষণশীল" },
      { id: "c", text: "সোলেনয়ডাল" },
      { id: "d", text: "শূন্য ভেক্টর" },
    ],
    correctOptionId: "b",
    explanation: "∇ × V = 0 হলে ভেক্টর ক্ষেত্রটি অঘূর্ণনশীল এবং বলক্ষেত্রটি একটি সংরক্ষণশীল বলক্ষেত্র হয়।",
  },
  {
    id: "hsc-phy-q5",
    topic: "ভেক্টর",
    marks: 1,
    text: "নৌকা চালনায় নদীর সবচেয়ে কম দূরত্বে অপর পাড়ে সরাসরি পৌঁছাতে হলে কোন কোণে যাত্রা করতে হবে?",
    options: [
      { id: "a", text: "cos⁻¹(−u/v)" },
      { id: "b", text: "sin⁻¹(u/v)" },
      { id: "c", text: "৯০°" },
      { id: "d", text: "৪৫°" },
    ],
    correctOptionId: "a",
    explanation: "সোজা অপর পাড়ে পৌঁছাতে লব্ধি বেগকে স্রোতের সাথে লম্ব হতে হয়, তাই cosα = −u/v বা α = cos⁻¹(−u/v)।",
  },
  {
    id: "hsc-phy-q6",
    topic: "ভেক্টর",
    marks: 1,
    text: "দুটি ভেক্টরের ক্রস গুণন A × B এর দিক কোন নিয়ম দ্বারা নির্ধারিত হয়?",
    options: [
      { id: "a", text: "ডানহাত স্ক্রু নিয়ম" },
      { id: "b", text: "ফ্লেমিংয়ের বামহাত নিয়ম" },
      { id: "c", text: "লেঞ্জের নিয়ম" },
      { id: "d", text: "অ্যাম্পিয়ারের সাঁতার নিয়ম" },
    ],
    correctOptionId: "a",
    explanation: "দুটি ভেক্টরের ক্রস গুণন ফলের দিক ভেক্টরদ্বয় যে তলে অবস্থিত তার সাথে লম্বভাবে ডানহাত স্ক্রু নিয়মে নির্ধারিত হয়।",
  },
];

export const EXAM_BANK: Record<string, Exam> = {
  // SSC Science - Physics
  "ssc-physics-live-01": {
    id: "ssc-physics-live-01",
    titleBn: "পদার্থবিজ্ঞান লাইভ পরীক্ষা: অধ্যায় ১–২",
    titleEn: "Physics Live Exam: Chapters 1–2",
    level: "ssc",
    stream: "science",
    subjectId: "physics",
    type: "live",
    durationSec: 15 * 60,
    negativeMark: 0.25,
    maxWarnings: 3,
    questions: [...PHYSICS_CH1, ...PHYSICS_CH2],
  },
  "ssc-physics-practice-ch1": {
    id: "ssc-physics-practice-ch1",
    titleBn: "অধ্যায় ১: ভৌত রাশি ও পরিমাপ",
    titleEn: "Chapter 1 Practice: Physical Quantities & Measurement",
    level: "ssc",
    stream: "science",
    subjectId: "physics",
    type: "practice",
    durationSec: 8 * 60,
    negativeMark: 0,
    maxWarnings: 3,
    questions: PHYSICS_CH1,
  },

  // SSC Science - Chemistry
  "ssc-chemistry-practice-ch1": {
    id: "ssc-chemistry-practice-ch1",
    titleBn: "অধ্যায় ৩: পদার্থের গঠন ও পারমাণবিক মডেল",
    titleEn: "Chapter 3 Practice: Structure of Matter",
    level: "ssc",
    stream: "science",
    subjectId: "chemistry",
    type: "practice",
    durationSec: 10 * 60,
    negativeMark: 0,
    maxWarnings: 3,
    questions: CHEMISTRY_CH3,
  },
  "ssc-chemistry-model-01": {
    id: "ssc-chemistry-model-01",
    titleBn: "রসায়ন পূর্ণাঙ্গ বোর্ড স্ট্যান্ডার্ড মডেল টেস্ট - ০১",
    titleEn: "Chemistry Full Board Model Test - 01",
    level: "ssc",
    stream: "science",
    subjectId: "chemistry",
    type: "model",
    durationSec: 12 * 60,
    negativeMark: 0.25,
    maxWarnings: 3,
    questions: CHEMISTRY_MODEL_01,
  },

  // SSC Science - Higher Mathematics
  "ssc-hmath-practice-ch1": {
    id: "ssc-hmath-practice-ch1",
    titleBn: "অধ্যায় ২: বীজগাণিতিক রাশি অনুশীলন",
    titleEn: "Chapter 2 Practice: Algebraic Expressions",
    level: "ssc",
    stream: "science",
    subjectId: "higher-math",
    type: "practice",
    durationSec: 10 * 60,
    negativeMark: 0,
    maxWarnings: 3,
    questions: HMATH_CH2,
  },
  "ssc-hmath-live-01": {
    id: "ssc-hmath-live-01",
    titleBn: "উচ্চতর গণিত স্পেশাল লাইভ চ্যালেঞ্জ",
    titleEn: "Higher Math Special Live Challenge",
    level: "ssc",
    stream: "science",
    subjectId: "higher-math",
    type: "live",
    durationSec: 15 * 60,
    negativeMark: 0.25,
    maxWarnings: 3,
    questions: HMATH_LIVE,
  },

  // SSC Science - Biology
  "ssc-biology-practice-ch1": {
    id: "ssc-biology-practice-ch1",
    titleBn: "অধ্যায় ২: জীবকোষ ও টিস্যু অনুশীলন",
    titleEn: "Chapter 2 Practice: Cell & Tissue",
    level: "ssc",
    stream: "science",
    subjectId: "biology",
    type: "practice",
    durationSec: 10 * 60,
    negativeMark: 0,
    maxWarnings: 3,
    questions: BIOLOGY_CH2,
  },
  "ssc-biology-model-01": {
    id: "ssc-biology-model-01",
    titleBn: "জীববিজ্ঞান পূর্ণাঙ্গ মডেল টেস্ট - ০১",
    titleEn: "Biology Full Model Test - 01",
    level: "ssc",
    stream: "science",
    subjectId: "biology",
    type: "model",
    durationSec: 12 * 60,
    negativeMark: 0.25,
    maxWarnings: 3,
    questions: BIOLOGY_MODEL_01,
  },

  // SSC Common - General Math
  "ssc-math-practice-ch1": {
    id: "ssc-math-practice-ch1",
    titleBn: "অধ্যায় ৩: বীজগাণিতিক রাশি ও মান নির্ণয়",
    titleEn: "Chapter 3 Practice: Algebraic Expressions",
    level: "ssc",
    stream: "science",
    subjectId: "math",
    type: "practice",
    durationSec: 10 * 60,
    negativeMark: 0,
    maxWarnings: 3,
    questions: MATH_CH3,
  },

  // HSC Science - Physics 1st Paper
  "hsc-physics-practice-ch1": {
    id: "hsc-physics-practice-ch1",
    titleBn: "পদার্থবিজ্ঞান ১ম পত্র: অধ্যায় ২ - ভেক্টর",
    titleEn: "HSC Physics 1st Paper: Chapter 2 - Vector",
    level: "hsc",
    stream: "science",
    subjectId: "physics-1",
    type: "practice",
    durationSec: 12 * 60,
    negativeMark: 0,
    maxWarnings: 3,
    questions: HSC_PHYSICS_VEC,
  },
};
